INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ['random_flip', 'random_translation', 'colorjitter', 'randomgrayscale', 'normalize']
  COLORJITTER_B: 0.4
  COLORJITTER_C: 0.4
  COLORJITTER_S: 0.4
  COLORJITTER_H: 0.4
  RGS_P: 0.5


MODEL:
  BACKBONE:
    PRETRAINED: True